server:
  port: 1111

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #原驱动com.mysql.jdbc.Driver已废弃
    url: jdbc:mysql://192.168.3.228:3306/dxh_mem?characterEncoding=UTF-8
    username: dxh
    password: Dxh2017$$
    type: com.alibaba.druid.pool.DruidDataSource

  #消息队列RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672  #不是15672,15672是管理端的端口
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #手动ack


